[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm config set audit false",
  "npm config set fund false",
  "npm install --legacy-peer-deps --no-audit"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx next start -H 0.0.0.0 -p ${PORT:-3000}"
